services:
  zookeeper:
    image: bitnami/zookeeper:3.7.0
    container_name: zookeeper-rrhh
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
  kafka:
    image: bitnami/kafka:3.1.0
    container_name: kafka-rrhh
    ports:
      - '9092:9092'
    environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    # Auto-create all required topics
    - KAFKA_CREATE_TOPICS=empleado.created:1:1,empleado.updated:1:1,empleado.deleted:1:1,servicioContrato.contrato.created:1:1,servicioContrato.contrato.updated:1:1,servicioContrato.contrato.deleted:1:1,servicioContrato.asistencia.created:1:1,servicioContrato.licencia.created:1:1,servicioContrato.vacacion.created:1:1,servicioEntrenamiento.scheduled:1:1,servicioEntrenamiento.updated:1:1,servicioEntrenamiento.evaluated:1:1,servicioEntrenamiento.turno.created:1:1,servicioNomina.nomina.generated:1:1,servicioNomina.added:1:1
    depends_on:
      - zookeeper
