@startuml
package "servicio-orquestador" {
  [SwaggerUI] ..> [SagaController]
  [SagaController] --> [StateMachine]
  [StateMachine] --> [EmpleadoClient]
  [StateMachine] --> [ContratoClient]
  [StateMachine] --> [DomainEventPublisher]
  [StateMachine] --> [SagaStateService]
  [StateMachine] --> [SagaOperationService]
}
@enduml
