@startuml
package "API Gateway" {
  [SwaggerUI] ..> [Gateway]
  [Gateway] --> [servicio-empleado]
  [Gateway] --> [servicio-contrato]
  [Gateway] --> [servicio-entrenamiento]
  [Gateway] --> [servicio-nomina]
  [Gateway] --> [servicio-consultas]
  [Gateway] --> [servicio-orquestador]
}
@enduml
