@startuml
actor Client
Client -> API_Gateway : POST /api/saga
API_Gateway -> "servicio-orquestador" : solicitud
"servicio-orquestador" -> "servicio-empleado" : crear empleado
"servicio-empleado" --> "servicio-orquestador" : empleado dto
"servicio-orquestador" -> "servicio-contrato" : crear contrato
"servicio-contrato" --> "servicio-orquestador" : contrato dto
"servicio-orquestador" -> Kafka : publicar saga completed
@enduml
